name: Deploy to GitHub Pages

on:
  push:
    branches:
      - gh-pages  # or your default branch

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history for proper commits

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'  # or your preferred version
          cache: 'npm'  # Cache npm dependencies
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Debug build output
        run: |
          echo "Listing build output files:"
          ls -la dist/
          echo "Checking for assets:"
          ls -la dist/assets/ || echo "No assets directory found"
        
      # Create necessary files for GitHub Pages
      - name: Prepare for deployment
        run: |
          touch dist/.nojekyll
          echo "www.priyadarsanmahendiran.com" > dist/CNAME
          
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages
          clean: false  # Don't remove existing files
          # Use this to debug if needed
          commit-message: "Deploy to GitHub Pages [ci skip]"